program
    = function
    ;

function
    = "int" identifier "(" "void" ")" "{" statement "}"
    ;

statement
    = "return" expression ";"
    ;

expression
    = integer_constant
    | unary_expression
    | binary_expression
    | "(" expression ")"
    ;

binary_expression
    = expression binary_operator expression
    ;

unary_expression
    = unary_operator expression
    ;

modifier_specifier
    = type_modifier
    | type_specifier
    | access_specifier
    ;

access_specifier
    = "external"
    | "internal"
    | "restrict"
    ;

type_modifier
    = "const"
    | "static"
    | "atomic"
    ;

type_specifier
    = "int"
    ;

binary_operator
    = "-"
    | "+"
    | "*"
    | "/"
    | "%"
    ;

unary_operator
    = "-"
    | "~"
    ;

identifier
    = ( alphanumeric | "_" )+
    ;

integer_constant
    = digit+
    ;

alphanumeric
    = ( letter | digit )+

digit
    = "0".."9"
    ;

letter
    = "a".."z" | "A".."Z"
    ;
